name: pygmt
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - pip
    - gmt=6.1.1
    - numpy
    - pandas
    - xarray
    - netCDF4
    - packaging
    - ipython
    - matplotlib
    - jupyter
    - pytest
    - pytest-cov
    - pytest-mpl
    - coverage
    - black
    - blackdoc
    - pylint
    - flake8
    - sphinx=2.2.1
    - sphinx_rtd_theme=0.4.3
    - sphinx-gallery
    - nbsphinx
